accounting/urls.py
from django.urls import path
from . import views


app_name = 'accounting'
urlpatterns = [
    path('', views.AccountingDashboardView.as_view(), name='accountingDashboard'),
]

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('', views.AccountsView.as_view(), name='accountsControl'),
]

inventory/urls.py
from django.urls import path
from . import views


app_name = 'inventory'
urlpatterns = [
    path('', views.inventoryDashboardView.as_view(), name='inventoryDashboard'),
]

main/urls.py
from django.urls import path
from . import views


app_name = 'main'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='homepage'),
    path('main/', views.MainPageView.as_view(), name='main'),
]

operations/urls.py
from django.urls import path
from . import views

app_name = 'operations'
urlpatterns = [
    path('', views.operationsView.as_view(), name='operations'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounting/', include('accounting.urls')),
    path('accounts/', include('accounts.urls')),
    path('operations/', include('operations.urls')),
    path('inventory/', include('inventory.urls')),
    path('purchase/', include('purchase.urls')),
    path('sales/', include('sales.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

purchase/urls.py
from django.urls import path
from . import views


app_name = 'purchase'
urlpatterns = [
    path('', views.purchaseHomeView.as_view(), name='purchaseView'),
]

sales/urls.py
from django.urls import path
from . import views


app_name = 'sales'
urlpatterns = [
    path('', views.salesDashboardView.as_view(), name='salesDashboard')
]

accounting/models.py
from django.db import models

# Create your models here.

accounts/models.py
from django.db import models

# Create your models here.

inventory/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Company(models.Model):
    cname = models.CharField(max_length=60)
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    logo = models.ImageField(upload_to="company_logos/")
    webpage = models.URLField(null=True, blank=True, max_length=200)
    const_center = models.PositiveSmallIntegerField()
    

    class Meta:
        verbose_name = "Company"
        verbose_name_plural = "Companys"

    def __str__(self):
        return self.cname

    def get_absolute_url(self):
        return reverse("Company_detail", kwargs={"pk": self.pk})
    



operations/models.py
from django.db import models

# Create your models here.

purchase/models.py
from django.db import models

# Create your models here.

sales/models.py
from django.db import models

# Create your models here.

accounting/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
# Create your views here.

class AccountingDashboardView(TemplateView):
    template_name = 'accounting_dashboard.html'



accounts/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.

class AccountsView(TemplateView):
    template_name = 'accounts.html'



inventory/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.

class inventoryDashboardView(TemplateView):
    template_name = 'inventory_dashboard.html'

main/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView 
from .models import Company
# Create your views here.

class HomePageView(TemplateView):
    template_name = 'homepage.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['company'] = Company.objects.all()
        return context
    
class MainPageView(TemplateView):
    template_name ='main.html'
    
    


operations/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
# Create your views here.

class operationsView(TemplateView):
    template_name = 'operations.html'

purchase/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.

class purchaseHomeView(TemplateView):
    template_name = 'purchase-dashboard.html'

sales/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class salesDashboardView(TemplateView):
    template_name = 'sales_dashboard.html'

accounting/templates/accounting_dashboard.html
{% extends "base.html" %}

{% block container %}
    <h1>accounting dashboard</h1>
{% endblock container %}

accounts/templates/accounts.html
{% extends "base.html" %}

{% block container %}
    accounts page
{% endblock container %}

inventory/templates/inventory_dashboard.html
{% extends "base.html" %}

{% block container %}
    <h2>Inventory</h2>
{% endblock container %}

main/templates/baseall.html


</div>
<div>
    {% block main %}
    
    {% endblock main %}
</div>

main/templates/homepage.html
{% extends "base.html" %}

{% block container %}
    <section>
        <div  style="display: flex; flex-direction: column ; column-gap: 5px"">
            {% for com in company %}
                    <div class="flex button-group gap-y-2" >
                        <img src="{{  com.logo.url}}" alt="img" height="100%" style=" margin-right: 15px"> 
                        <div class="flex; flex-col; text-start" style="text-align: start">
                            <h2 style="font-size: 1.2rem">{{ com }}</h2>
                            <div>
                                <p>Location: {{ com.location }}</p>
                                <p>Email: {{ com.email }}</p>
                                {% comment %} <p>{{}}</p> {% endcomment %}
                            </div>
                        </div>
                    </div>
            {% endfor %}
        </div>
    </section>
{% endblock container %}

main/templates/main.html
{% extends "base.html" %}


{% block container %}
    {{block.super}}
    <h2>Here is child page</h2>
{% endblock container %}

operations/templates/operations.html
{% extends "base.html" %}

{% block container %}
    <h2>Containers</h2>
{% endblock container %}

purchase/templates/purchase-dashboard.html
{% extends "base.html" %}

{% block container %}
<div style='align-text:center; color: green'>

    <h2>purchase gjgjh ghjhkj kjhkjhjk kjhkjhk kjhkjoioi cdsfds .mikpoi khkjh fhgfhgf gfgf</h2>
</div>
{% endblock container %}

sales/templates/sales_dashboard.html
{% extends "base.html" %}

{% block container %}
    <h2>Sales dashboard</h2>
{% endblock container %}

templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'src/input.css' %}">
    <link rel="stylesheet" href="{% static 'src/components.css' %}">
    <link rel="stylesheet" href="{% static 'src/formcss.css' %}">
    <link rel="stylesheet" href="{% static 'src/main.css' %}">
    {% tailwind_css %}
    <title>Document</title>
</head>
<body class="inter flex min-h-screen">
    <aside class="px-3 py-4 border-e">
        <section class="flex flex-col justify-between h-[95vh] py-3">
            <div>
                <a href="{% url 'main:homepage' %}" class="flex flex-col mb-4 gap-y-3">
                    <img src="{% static 'images/logo/inventory-management.png' %}" alt="" width='50px' class="m-auto py-2">
                    <div class="text-blue-700 text-center text-sm hidden md:block sm:text-lg lg:text-xl  text-wrap xl:text-nowrap  font-extrabold">Gulf Gate</div>
                    <div class="text-blue-700 text-center text-sm hidden md:block sm:text-lg lg:text-xl  text-wrap xl:text-nowrap  font-extrabold ">Main Warehouse</div>
                </a>
                <hr>
                <section class="flex flex-col my-3 gap-y-5">
                    {% comment %} <a href="" class="text-blue-600 font-semibold sm:text-lg ">Home</a> {% endcomment %}
                    <a href="{% url 'purchase:purchaseView' %}" class="text-gray-600 font-semibold sm:text-lg ">
                        <div class="flex gap-x-2">
                            <span class="m-auto md:hidden lg:m-0 lg:inline-block"><img src="{% static 'images/logo/purchase.png' %}" alt="accounting" width='20px'></span>
                            <span class="hidden md:inline-block leading-5">Purchase</span>
                        </div>
                    </a>
                    <a href="{% url 'inventory:inventoryDashboard' %}" class="text-gray-600 font-semibold sm:text-lg ">                
                        <div class="flex gap-x-2">
                            <span class="m-auto md:hidden lg:m-0 lg:inline-block"><img src="{% static 'images/logo/inventory.png' %}" alt="production" width='20px'></span>
                            <span class="hidden md:inline-block leading-5">Inventory</span>
                        </div>
                    </a>
                    <a href="{% url 'operations:operations' %}" class="text-gray-600 font-semibold sm:text-lg ">
                        <div class="flex gap-x-2">
                            <span class="m-auto md:hidden lg:m-0 lg:inline-block"><img src="{% static 'images/logo/production.png' %}" alt="production" width='20px'></span>
                            <span class="hidden md:inline-block leading-5">Production</span>
                        </div>
                    </a>
                    <a href="{% url 'accounting:accountingDashboard' %}" class="text-gray-600 font-semibold sm:text-lg ">
                        <div class="flex gap-x-2">
                            <span class="m-auto md:hidden lg:m-0 lg:inline-block"><img src="{% static 'images/logo/accounting.png' %}" alt="accounting" width='20px'></span>
                            <span class="hidden md:inline-block leading-5">Accounting</span>
                        </div>
                    </a>
                    <a href="{% url 'sales:salesDashboard' %}" class="text-gray-600 font-semibold sm:text-lg ">
                        <div class="flex gap-x-2">
                            <span class="m-auto md:hidden lg:m-0 lg:inline-block"><img src="{% static 'images/logo/sales.png' %}" alt="sales" width='20px'></span>
                            <span class="hidden md:inline-block leading-5">Sales</span>
                        </div>
                    </a>
                </section>

            </div>
            <div>
                <a href="" class="flex gap-x-1 text-blue-500">
                    <span class="m-auto md:m-0"><img src="{% static 'images/logo/settings.png' %}" alt="sales" width='20px'></span>
                    <span class="hidden md:inline-block leading-5">Settings</span>
                </a> 
                <p class="w-full md:ms-3  text-gray-600 "><span class="m-auto  hidden lg:inline-block">version</span> <span class="m-auto inline-block lg:hidden">v</span> <span>1.0</span> </p>               
            </div>
        </section>
    </aside>

    <main class="flex-1">
        <nav class="bg-sky-800 text-gray-500 py-2 px-10 flex justify-end border-b border-slate-100 shadow-sm">
            <a href="{% url 'accounts:accountsControl' %}" class="text-white">Login</a>
        </nav>
        <div class="px-3 py-2">
            {% block container %}
            sadasd
            {% endblock container %}
        </div>
    </main>
</body>
</html>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>